[package]
name = "fadeluc-123/echo"
description = "A React like structured sound module, basically React for sound! Visit Whiteoak Studios for documentation: https://github.com/Whiteoak-Studios/Echo"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
authors = [
    "Michael Sumner <mike@whiteoak.studio>"
]

include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml"
]

[dependencies]
Promise = "evaera/promise@^4.0.0"
Sift = "csqrl/sift@0.0.9"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"