[package]
name = "fadeluc-123/echo"
description = "A reactive sound module, used to minimize the amount of datamodels to be kept track of. Visit Whiteoak Studios for documentation: https://github.com/Whiteoak-Studios/Echo"
version = "7.8.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
authors = [
    "Michael Sumner <mike@whiteoak.studio>"
]

include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml",
    "src/Modules",

    "src/Modules/Binds",
    "src/Modules/Binds/Area.lua",

    "src/Modules/Classes",
    "src/Modules/Classes/Signal.lua",
    "src/Modules/Classes/Cache.lua",
    "src/Modules/Spring.lua",

    "src/Modules/ZoneTracker",
    "src/Modules/ZoneTracker/AreaV2.lua",
    "src/Modules/ZoneTracker/AreaV7.lua",
    "src/Modules/ZoneTracker/init.lua",
    "src/Modules/ZoneTracker/ObjectTracker.lua",

    "src/Modules/Events",
    "src/Modules/Events/Ended.lua",
    "src/Modules/Events/Loaded.lua",
    "src/Modules/Events/Looped.lua",
    "src/Modules/Events/Playing.lua",

    "src/Modules/Actions",
    "src/Modules/Actions/Pause.lua",
    "src/Modules/Actions/Play.lua"
]

[dependencies]
Promise = "evaera/promise@^4.0.0"
Cache = "fadeluc-123/objectcache@2.4.0"
Sift = "csqrl/sift@0.0.11"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"